irc: fix handling "Request SendMessageRequest(...) had missing message mapping Updates(...)" channel-posting ban
Might lead to a new "You're banned from sending messages in supergroups/channels" error getting raised,
or maybe it's just my account that got extra restrictions applied since the original error.
Seems similar to https://github.com/LonamiWebs/Telethon/issues/4167 report in telethon.

[W messageparse:207] Request SendMessageRequest(...) had missing message mapping Updates(...)
[E ioloop:778] Exception in callback functools.partial(<function TCPServer._handle_connection.<locals>.<lambda> at ...
Traceback (most recent call last):
  File "venv/lib/python3.13/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "venv/lib/python3.13/site-packages/tornado/tcpserver.py", line 387, in <lambda>
    gen.convert_yielded(future), lambda f: f.result()
                                           ~~~~~~~~^^
  File "irgramd/irgramd", line 55, in handle_stream
    await self.irc_handler.run(stream, address)
  File "irgramd/irc.py", line 100, in run
    await handler(user, **params)
  File "irgramd/irc.py", line 419, in handle_irc_privmsg
    mid = self.tg.mid.num_to_id_offset(telegram_id, tg_msg.id)
                                                    ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'